### ISSUE TITLE
Clarity regarding MPC tutorial example NLOC_MPC

### ISSUE THREAD

**Issue by NishanthARao** [ethz-adrl/control-toolbox#207]
I have a custom non-linear system that I have described in a separate ```.hpp``` file using the ```ControlledSystem``` class. I want to design an NMPC controller for it. I had a few doubts regarding the standard MPC example given on the [tutorials page.](https://ethz-adrl.github.io/ct/ct_doc/doc/html/optcon_tut_mpc.html). 

1) The state ```x0``` is being initialized randomly and then multiplied by 0.1. Is this a noise value, or the current state of the system (makes no sense if it's the current state of the system) If it's a noise signal, then why are we passing it to the ```finishIteration``` function as the current state? (as described in the [reference class](https://ethz-adrl.github.io/ct/ct_optcon/doc/html/classct_1_1optcon_1_1MPC.html#aac61f32fa2e1f7a859696c21dea5acf4)).

2) Why is a new policy being created every time in the loop? Does ```finishIteration``` assign a new value to this ```newPolicy``` variable at every loop iteration?

3) I want to design the MPC say for 10 seconds. The sampling time is say 0.05 seconds and the prediction horizon is say  20 steps. Hence the time horizon for the optimal control problem becomes 1 second. According to the code, timeHorizonReached will be true after 1s, and the for loop will break. But I want to run it for 10s again, in a receding horizon fashion. How can I modify the code? 

I am truly grateful for any suggestions/answers as I am stuck with these questions and how to apply them to my problem definition.

Thanks in advance.

**Comment by rubengrandia** [comment]
Hi,
I have been out of this code base for a while, but looking at the example you mention I have a few comments that might help you on your way.

1. I agree with you that it would be more realistic to set here some x_meas = x + noise. Currently it just sets a random state variable. Either way, for the other iterations (i >0), you would typically need to implement some forward simulation (+ state estimation) to obtain a realistic future state. All of that was left away in this example to just focus on solving the MPC problem given a certain state. One simple way to emulate this, is to interpolate the predicted state trajectory contained in newPolicy at the shifted time, and add some noise around that.

2. yes, newPolicy serves as an output parameter of finishIteration. Because the provided x0 and t change every loop, the optimal policy should change accordingly.

3. Notice how the current example uses MPC_MODE::FIXED_FINAL_TIME in the settings. This means that when the set time horizon is reached, the problem is done. From your description it seems you either want MPC_MODE::RECEDING_HORIZON_WITH_FIXED_FINAL_TIME (here you can have a 10s problem, but with a 1s MPC horizon) or MPC_MODE::CONSTANT_RECEDING_HORIZON (here you just have the 1s horizon and potentially run the controller for infinite time). Have a look at the documentation of MPC_NODE for further details.

**Comment by NishanthARao** [comment]
@rubengrandia Thanks a lot for your response. I figured out the MPC_MODES and how to use them, but I wasn't sure of my method and how I was using it. Thanks a lot for confirming these modes.
