### ISSUE TITLE
Many headers do not #include their dependencies

### ISSUE THREAD

**Issue by Scarabytes** [ethz-adrl/control-toolbox#49]
For example, StateVector extends Eigen::Matrix but includes nothing at all.
It shouldn't be required for the user of a header to include it's dependencies.

I know that there are collective headers that include everthing needed, but they also include a lot of unneeded stuff that just increases compile time.

**Comment by markusgft** [comment]
Hi @Scarabytes, 
Thank you for your report. I agree that there could be a more consistent design regarding includes in header files in some places. Let me briefly comment on this:

- Our original design intention is indeed to let users include the convenience/bulk/collective includes. 

- First of all, it should not significantly increase your compile time, performance wise it is perfectly fine to include the collective header. Just because the header is there, it does not automatically mean that the classes get compiled -- only what you explicitly instantiate in your executable or library gets compiled, so you do not need to worry about that.

- In fact, there is a solid reason why you should only use the collective include and stick with it. Certain Eigen-headers and CppAD headers need to be included in a particular order for being fully compatible with automatic differentiation and code generation. If you include individual headers at your personal convenience, you risk messing up that order and your code might not compile at all.

I hope this helps!
